// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cqihraipvhnsudlilyzr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNxaWhyYWlwdmhuc3VkbGlseXpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4ODY5NjksImV4cCI6MjA1OTQ2Mjk2OX0.gusZHGASUP3hrrJmoWgQvUX8JbaWiKFNjcak867LLdA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);